# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2022 CERN.
#
# Invenio is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * 6'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
          python-version: [3.9]
          requirements-level: [pypi]
          db-service: [postgresql13, postgresql14]
          search-service: [opensearch2,elasticsearch7]
          include:

            - search-service: opensearch2
              SEARCH_EXTRAS: "opensearch2"

            - search-service: elasticsearch7
              SEARCH_EXTRAS: "elasticsearch7"

    env:
      DB: ${{ matrix.db-service }}
      SEARCH: ${{ matrix.search-service }}
      EXTRAS: tests,${{matrix.SEARCH_EXTRAS}},postgresql,indexer,records

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.cfg

      - name: Install dependencies
        run: |
          pip install ".[$EXTRAS]"
          pip freeze
          docker version

      - name: Run backend tests
        run: |
          ./run-tests.sh
